---

- name: Install ffmpeg
  apt: name=ffmpeg update_cache={{ update_apt_cache }} force=yes state=installed
  tags: packages

- include: create_users_and_groups.yml

- include: setup_virtualenv.yml
  tags: virtualenv

- include: setup_git_repo.yml
  tags: deploy

- include: setup_django_app.yml
  tags: deploy
  
- include: setup_supervisor.yml

- include: setup_nginx.yml
  tags: nginx

- include: set_file_permissions.yml
  tags: deploy

- include: setup_cron_jobs.yml
